### ISSUE TITLE
Should be able to delete content

### ISSUE THREAD

**Issue by tivac** [tivac/crucible#12]
Right now the delete button is there but non-functional. Should almost certainly have a "confirm" requirement.

**Comment by kevinkace** [comment]
An alternative UX to a confirmation modal is a notification with an option to undo.

**Comment by tivac** [comment]
Yeah, undo will be important. I suspect eventually it should be:

1. Save current data as new revision
2. Remove from active content
3. Store reference in some sort of Garbage Can/Recycle bin alongside date it was removed
4. After some predetermined amount of time (2 weeks?) items in the bin are dumped completely, including all their revisions.

But for now it can just dumbly remove stuff and that isn't world-ending yet.
