### ISSUE TITLE
Minor bug: Strange behavior when hitting `enter` in Title field.

### ISSUE THREAD

**Issue by ctcleary** [tivac/crucible#131]
If you hit `enter`, then `backspace` while in the `Title` field while on the `content-edit` side of things, any characters on the right side of your cursor becomes oversized for some reason.

Super minor bug, nothing weird gets saved as far as I can tell.

Repro:
* Enter a title like "This Is A Title"
  * Put cursor behind "A"
  * Hit enter
    * "A Title" moves to a new line, is wrapped in a `<div>` tag.
  * Hit backspace
    * "A Title" returns to the same line, is wrapped in a `<span>` tag with an inline `style="font-size: 2em;"`

Just for giggles, you can keep hitting enter/backspace at different places and each new section will be wrapped in its own `<span>` tag, leaving the old one(s) behind on the first line.

**Expected behavior?**

I would guess that hitting `enter` while in the title field should remove focus / `blur` the field.

**Comment by tivac** [comment]
Sounds like some `contenteditable` bullshit. Should probably just change that to a normal `<input>` instead.

**Comment by ctcleary** [comment]
In my recent big change, I altered the title to be an input rather than `contenteditable` so this should be resolved.
