### ISSUE TITLE
Publish button should check validity of required fields

### ISSUE THREAD

**Issue by ctcleary** [tivac/crucible#138]
At the moment, it's possible to set an item to "Published" even if there are required fields with no data.

Ideally, publish button should refuse to do its thing and also inform the user of the missing/required information.

**Comment by tivac** [comment]
It definitely used to require that fields be valid. That's why https://github.com/tivac/crucible/blob/master/src/pages/content-edit/index.js#L111-L120 exist, so the actual DOM form reference could be checked for validity.

**Comment by ctcleary** [comment]
I can dig into it once I get some other things out of the way, just wanted to mark it down before I forgot about it.

**Comment by ctcleary** [comment]
Started work on this a (business) day or two ago.  Forgot to assign myself when I started.
