### ISSUE TITLE
npm install crucible failing

### ISSUE THREAD

**Issue by ssiddi28** [tivac/crucible#177]
Installation is failing using `npm install crucible`

here are the errors:

- npm WARN enoent ENOENT: no such file or directory, open '/*/package.json'
- npm WARN test No description
- npm WARN test No repository field.
- npm WARN test No README data
- npm WARN test No license field.

**Comment by tivac** [comment]
Sounds like you installed crucible in a directory without a `package.json` file. I just tested this in a similar directory and here's the output I saw.

```bash
PS C:\> npm i crucible
C:\
`-- crucible@0.3.5

npm WARN enoent ENOENT: no such file or directory, open 'C:\package.json'
npm WARN Desktop No description
npm WARN Desktop No repository field.
npm WARN Desktop No README data
npm WARN Desktop No license field.
```

but it still installed fine into `C:\node_modules\crucible`. Are you sure it didn't install correctly?

**Comment by ssiddi28** [comment]
![screen shot 2017-04-28 at 8 08 16 am](https://cloud.githubusercontent.com/assets/4510613/25529940/e1f9ed38-2be9-11e7-98bd-51ca60362d8a.png)

Above is the difference between a pulled down version vs the `npm install crucible` version. 

Say I tried to install in an empty directory. I get a node_modules folder, and then a crucible folder. The crucible folder is the the one on the right in the above pic. I then get the errors you also saw.

**Comment by tivac** [comment]
Yes, that's how `npm install` works. It always installs to a `./node_modules/<package_name>` folder.

The version from npm has less files because it doesn't need all the infrastructure to build/develop crucible. It's already packaged up and ready to run in `./gen/index.js` and `./gen/index.css`

I've verified that the version from NPM installs and works correctly.

**Comment by ssiddi28** [comment]
Thank you for clearing that up for me @tivac . I thought something was wrong because opening index.html from the installed version shows a blank page. 

..I'm probably just doing something wrong

**Comment by tivac** [comment]
Did you  create & configure the crucible `config.js` file? Make sure you've followed all the steps in the [Installation Guide](https://github.com/tivac/crucible/#installation).

**Comment by ssiddi28** [comment]
I did do that. The most I could get up and running is 

<img width="1361" alt="screen shot 2017-04-28 at 12 28 08 pm" src="https://cloud.githubusercontent.com/assets/4510613/25539733/2aab98a0-2c0e-11e7-8643-6eae9567d31f.png">


But nothing happens when clicking anywhere

**Comment by tivac** [comment]
Looks like the last time the UI got tweaked the "no schemas exist case" didn't get accounted for.

You should be able to stick `/content/new` at the end of the URL and use that to add a schema, in theory.

Going to close out this issue, open new ones for more specific feedback/issues please.
