### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by corysimmons** [tivac/crucible#180]
Would like to see the styles without having to install/config/run.

**Comment by kevinkace** [comment]
Here are some screenshots from a current (small) setup:

![crucible-home](https://user-images.githubusercontent.com/532448/29679769-62c3bf46-88b7-11e7-88e7-605602c29d39.png)
![crucible-content](https://user-images.githubusercontent.com/532448/29679767-62c0f8b0-88b7-11e7-868b-1169abbf0f64.png)
![crucible-edit](https://user-images.githubusercontent.com/532448/29679770-62c53ad8-88b7-11e7-9e3f-986865216bb7.png)
![crucible-edit-schema](https://user-images.githubusercontent.com/532448/29679768-62c37c48-88b7-11e7-89c7-165e76ab6dd1.png)

**Comment by corysimmons** [comment]
Nice. Thank you.
