### ISSUE TITLE
Need a logo

### ISSUE THREAD

**Issue by voodoochild** [tivac/crucible#28]
Everyone knows that any good home-spun CMS needs a natty logo to go with the cool name.

I suggest that we hit up some ANet Photoshop wizards to come up with something based on this:

![Crucible](https://guildcrest.files.wordpress.com/2011/02/crucible.jpg)

I would also be okay with someone coming up with a slogan that has something to do with pouring molten hot content.

**Comment by kevinkace** [comment]
> A CMS hotter than my mixtape :fire:

And for the logo certainly that's something Lawton should handle...

**Comment by tivac** [comment]
I would love an authentic @lye logo :smile_cat:

**Comment by lye** [comment]
![crucible](https://cloud.githubusercontent.com/assets/921652/12213718/8ed4ca7a-b632-11e5-8f4e-b166c786de28.png)

**Comment by voodoochild** [comment]
So beautiful :joy:
