### ISSUE TITLE
Needs a better layout

### ISSUE THREAD

**Issue by tivac** [tivac/crucible#34]
http://purecss.io/layouts/email/ seems like a good inspiration.

![screen shot 2016-01-11 at 09 53 20](https://cloud.githubusercontent.com/assets/49545/12241706/78bf94e0-b849-11e5-9454-1fad377ff932.png)

**Comment by kevinkace** [comment]
Some progress last night.

![cruc](https://cloud.githubusercontent.com/assets/532448/12270387/bdbfdb38-b90a-11e5-8734-fc85045c1d98.png)
![cruc](https://cloud.githubusercontent.com/assets/532448/12270389/c20aebc4-b90a-11e5-83dc-4aa30497f8e7.gif)

**Comment by tivac** [comment]
That's a nice-looking start! A little worried about spacing on that middle column once it gets all the details but I'm sure there's a solution.
