### ISSUE TITLE
Need ability to backup DB

### ISSUE THREAD

**Issue by kevinkace** [tivac/crucible#38]
Firebase offers this but only on their $150/month plan.

Automated backups are cooler, but perhaps a button to backup to S3 would suffice for now.
Might be nice to store the last backup date, and nag users if it's been more than 5 days.

**Comment by tivac** [comment]
There's a REST API to download everything in an importable format, dunno that we would want to expose it via the UI though. Seems like something better suited to an automated process that is entirely separate from crucible.

And yes, their backup solution only being on the expensive plans is lame.

**Comment by tivac** [comment]
Won't be an option in the UI for this, but there's a couple of options:

1. Use the `firebase-tools` npm package that installs the `firebase` command.

    `firebase data:get / > firebase.json -f blazing-torch-1111`

2. Use the REST API

    `https://blazing-torch-1111.firebaseio.com//.json?format=export`

Set one of those up a repeating task and should be good to go.
