### ISSUE TITLE
Checkboxes should support multiple options

### ISSUE THREAD

**Issue by tivac** [tivac/crucible#47]
They should act like `radio`, IMO.

**Comment by voodoochild** [comment]
When you say that they should act like radio buttons do you just mean how they're configured in the schema JSON, or should you only be able to check one of a group of checkboxes?

**Comment by tivac** [comment]
How they're configured, so you can add multiple options to a single checkbox "field". It'd represent the data in firebase as an array of values.

Not totally convinced this is necessary, but it still seems valuable to ponder.

**Comment by kevinkace** [comment]
This would be useful in the case of using checkboxes for setting which langs to publish.
