### ISSUE TITLE
Select doesn't support strings for options value

### ISSUE THREAD

**Issue by kevinkace** [tivac/crucible#64]
Not sure if this was never the intention (in which case the readme needs an update), or just doesn't yet work.

```js
{
  type : "select",
  options : {
    one : "one", // doesn't work
    two : {
      value : "two" // works
  }
}
```

**Comment by tivac** [comment]
This should be supported, as that is a way more friendly way to enter those. Crucible should convert them behind-the-scenes into the more verbose format.

**Comment by tivac** [comment]
This is working fine for me locally, re-open w/ more details if you're still seeing failures.
