### ISSUE TITLE
Unable to save when a text field within a tab is empty

### ISSUE THREAD

**Issue by Ryan-McMillan** [tivac/crucible#95]
I've got a text field within a tab, and whenever it's empty and I try to save I get this error:

Uncaught Error: Firebase.set failed: First argument contains undefined in property 'content.loadinginfo.-KAwBZeZCI-5gwcV3wWX.fields.468x60.text.de.body'

**Comment by Ryan-McMillan** [comment]
To trigger this error, the field has to have been saved with some value first, then attempt to remove it.

**Comment by kevinkace** [comment]
Running into this issue as well.

Here the value is set to `undefined`, which then FB barfs on.
https://github.com/tivac/crucible/blob/master/src/lib/update.js#L10

I had updated to unset the field, but reverted for probably reasons?
https://github.com/tivac/crucible/commit/829c22e3e36a1ae441cd4aaba04b076f04696db8

**Comment by tivac** [comment]
Based on the firebase docs it looks like I should use [`null`](https://www.firebase.com/docs/web/api/firebase/set.html#firebase_set) instead of `undefined`.
