### ISSUE TITLE
Can't set a default value for number inputs

### ISSUE THREAD

**Issue by Ryan-McMillan** [tivac/crucible#96]
It's not possible to set a default value for numbers (and probably other input types).  When setting "value" under attrs, the value can't be changed in the input.

`maxlevel : {
     type  : "number",
        attrs : {
             min   : 1,
             max   : 80,
             value : 80
        }
}`

**Comment by tivac** [comment]
https://github.com/tivac/crucible/blob/master/src/types/lib/input.js#L30-L42

It's because it's merging in `attrs` over the top of any user/db specified value, which is... well stupid's a good word.
